modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/McJtyMods/Restrictions/issues"
displayURL="http://github.com/McJtyMods/Restrictions/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="restrictions"
version="${file.jarVersion}"
displayName="Restrictions"
#updateJSONURL="http://myurl.me/" #optional
description='''
A vanilla+ style mod that adds some blocks to help push/pull mobs and players
'''

[[dependencies.restrictions]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.restrictions]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.15-4.1.7,)"
    ordering="AFTER"
    side="BOTH"
